### ISSUE TITLE
Adding additional information to the Home Assistant MQTT Auto Discovery messages

### ISSUE THREAD

**Issue by fkroepfl** [thorrak/tiltbridge#248]
The aim is to optimize the visualization of tilt devices and sensor data in the Home Assistant by modifying the auto discovery messages.

### **Initial situation using the "Tilt Blue" example:**

```
homeassistant/sensor/tiltbridge_tilt_Blue/temperature/config

{
  "device": {
    "identifiers": "Blue",
    "name": "Tilt Blue"
  },
  "dev_cla": "temperature",
  "unit_of_meas": "°C",
  "ic": "mdi:thermometer",
  "stat_t": "tiltbridge/tilt_Blue",
  "name": "Tilt Temperature - Blue",
  "val_tpl": "{{value_json.Temp}}",
  "uniq_id": "tiltbridge_tiltBlueT"
}

```
### **Suggestion:**

**1) Add an attribute to the sensor status as secondary information, e.g.: the timestamp**

References found to: `state.last_updated` & `state.last_changed`

- https://www.home-assistant.io/docs/configuration/state_object/
- https://www.home-assistant.io/dashboards/entities/#secondary_info

If the sensor now has "temperature" as the status and, for example, the timestamp as an attribute, an update with the same temperature but a different timestamp will update last_updated but not last_changed, as only the attribute has been updated.

The same would of course also apply to the "Specific density".

_Here is an example of the effect in the entity card_

![image](https://github.com/thorrak/tiltbridge/assets/6333880/b9bbbe61-52b6-4dc4-8b83-54d5be052524)

**2) Additional information about the device to which this sensor belongs**

References found for configuration variable: device

- https://www.home-assistant.io/integrations/sensor.mqtt/#device

Could be of interest IMHO:
- https://www.home-assistant.io/integrations/sensor.mqtt/#configuration_url
- https://www.home-assistant.io/integrations/sensor.mqtt/#manufacturer
- https://www.home-assistant.io/integrations/sensor.mqtt/#model
- https://www.home-assistant.io/integrations/sensor.mqtt/#via_device

**Comment by thorrak** [comment]
As I mentioned, I don't use either MQTT or Home Assistant -- but at one point I set up a HAST instance with the intent of trying to get it working with TiltBridge. Unfortunately, Home Assistant Autodiscovery wasn't (isn't?) the best documented at the time, and so I ended up giving up.

While I can't promise to get this one fixed soon, I'll give it a shot when I have some time.

**Comment by fkroepfl** [comment]
FYI: With the following manual configuration (YAML/JSON) it was possible to choose the display of the sensor status according to the HA options (screenshot).

I hope it helps when thinking about how to integrate this into the code.

![image](https://github.com/thorrak/tiltbridge/assets/6333880/557acbfa-b106-4d82-8dfe-cf2ce76281f3)

![image](https://github.com/thorrak/tiltbridge/assets/6333880/4e8aece9-3edd-4ac7-bc8c-52a352e31aac)


**mqtt.yaml**
```
sensor:
# Red Tilt
# Temperature
  - name: "MyTilt|Red Temperature"
    unique_id: "myTiltRedTemperature"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-water"
    state_topic: "tiltbridge/tilt_Red"
    value_template: "{{value_json.Temp}}"
    json_attributes_topic: "tiltbridge/tilt_Red"
    json_attributes_template: >
      { "Uptime": "{{ value_json.timeStamp }}" }
    device:
      name: "Tilt Red"
      identifiers: "Red"
      model: "TILT™ HYDROMETER AND THERMOMETER"
      manufacturer: "Baron Brew Equipment LLC"
      configuration_url: "http://tiltbridge.local/"
      via_device: "TiltBridge"
      sw_version: "v1.2.1"
      suggested_area: "Brewery"

# Specific Gravity
  - name: "MyTilt|Red Specific Gravity"
    unique_id: "myTiltRedSpecificGravity"
    unit_of_measurement: "SG"
    icon: "mdi:slope-downhill"
    state_topic: "tiltbridge/tilt_Red"
    value_template: "{{value_json.SG}}"
    json_attributes_topic: "tiltbridge/tilt_Red"
    json_attributes_template: >
      { "Uptime": "{{ value_json.timeStamp }}" }
    device:
      name: "Tilt Red"
      identifiers: "Red"
      model: "TILT™ HYDROMETER AND THERMOMETER"
      manufacturer: "Baron Brew Equipment LLC"
      configuration_url: "http://tiltbridge.local/"
      via_device: "TiltBridge"
      sw_version: "v1.2.1"
      suggested_area: "Brewery"

# Uptime
  - name: "MyTilt|Red Uptime"
    unique_id: "myTiltRedUptime"
    unit_of_measurement: "s"
    icon: "mdi:timer-sync"
    state_topic: "tiltbridge/tilt_Red"
    value_template: "{{ value_json.timeStamp }}"
    device:
      name: "Tilt Red"
      identifiers: "Red"
      model: "TILT™ HYDROMETER AND THERMOMETER"
      manufacturer: "Baron Brew Equipment LLC"
      configuration_url: "http://tiltbridge.local/"
      via_device: "TiltBridge"
      sw_version: "v1.2.1"
      suggested_area: "Brewery"

```

**JSON (yaml converted)**
```
[
  {
    "name": "MyTilt|Red Temperature",
    "unique_id": "myTiltRedTemperature",
    "unit_of_measurement": "°C",
    "icon": "mdi:thermometer-water",
    "state_topic": "tiltbridge/tilt_Red",
    "value_template": "{{value_json.Temp}}",
    "json_attributes_topic": "tiltbridge/tilt_Red",
    "json_attributes_template": "{ \"Uptime\": \"{{ value_json.timeStamp }}\" }\n",
    "device": {
      "name": "Tilt Red",
      "identifiers": "Red",
      "model": "TILT™ HYDROMETER AND THERMOMETER",
      "manufacturer": "Baron Brew Equipment LLC",
      "configuration_url": "http://tiltbridge.local/",
      "via_device": "TiltBridge",
      "sw_version": "v1.2.1",
      "suggested_area": "Brewery"
    }
  },
  {
    "name": "MyTilt|Red Specific Gravity",
    "unique_id": "myTiltRedSpecificGravity",
    "unit_of_measurement": "SG",
    "icon": "mdi:slope-downhill",
    "state_topic": "tiltbridge/tilt_Red",
    "value_template": "{{value_json.SG}}",
    "json_attributes_topic": "tiltbridge/tilt_Red",
    "json_attributes_template": "{ \"Uptime\": \"{{ value_json.timeStamp }}\" }\n",
    "device": {
      "name": "Tilt Red",
      "identifiers": "Red",
      "model": "TILT™ HYDROMETER AND THERMOMETER",
      "manufacturer": "Baron Brew Equipment LLC",
      "configuration_url": "http://tiltbridge.local/",
      "via_device": "TiltBridge",
      "sw_version": "v1.2.1",
      "suggested_area": "Brewery"
    }
  },
  {
    "name": "MyTilt|Red Uptime",
    "unique_id": "myTiltRedUptime",
    "unit_of_measurement": "s",
    "icon": "mdi:timer-sync",
    "state_topic": "tiltbridge/tilt_Red",
    "value_template": "{{ value_json.timeStamp }}",
    "device": {
      "name": "Tilt Red",
      "identifiers": "Red",
      "model": "TILT™ HYDROMETER AND THERMOMETER",
      "manufacturer": "Baron Brew Equipment LLC",
      "configuration_url": "http://tiltbridge.local/",
      "via_device": "TiltBridge",
      "sw_version": "v1.2.1",
      "suggested_area": "Brewery"
    }
  }
]
```
